/**:
  ros__parameters:
    image_topic: "carla/hero/front/image"
    imu_topic: "carla/hero/imu"
    weight_file: "home/fusion-VO-ws/src/fusion-VO/weights/superpoint_lightglue_320w_240h.engine"
    resize_width: 320
    resize_height: 240
