/**:
  ros__parameters:
    image_topic: "carla/hero/front/image"
    imu_topic: "carla/hero/imu"
    weight_file: "/weights/superpoint_lightglue_320_240.engine"
    imu_frame: "imu_link"
    camera_frame: "carla/front"
    base_frame: "base_link"
    map_frame: "map"
    resize_width: 320
    resize_height: 240
    num_keypoints: 1024 #According to the NN model
    fx: 320.0
    fy: 320.0
    cx: 320.0
    cy: 240.0
    absolute_coords: false
    pose_initializer: "rviz"
